# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
     
    - name: Get Latest Release
      id: latest_version
      uses: abatilo/release-info-action@v1.3.0
      with:
        owner: ruizrube
        repo: example-spring-vaadin14
    
    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
        JARO_NAME: '${{ steps.latest_version.outputs.latest_tag }}.jar'
          
    - name: Example of consumption of the output
      env:
        LATEST: ${{ steps.latest_version.outputs.latest_tag }}
        LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
      run: |
        echo "Version $LATEST was released at $LATEST_DATE"
          

    - name: Build with Maven
      env:
        LATEST: ${{ steps.latest_version.outputs.latest_tag }}
      working-directory: ./example-spring-vaadin14
      run: mvn -B package -Djar.finalName=app.jar

    - name: Publish to GitHub Packages Apache Maven
      working-directory: ./example-spring-vaadin14
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
      
    - name: Deploy to EB
      env:
        LATEST: ${{ steps.latest_version.outputs.latest_tag }}
      uses: einaregilsson/beanstalk-deploy@v11
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: example-spring-vaadin14
        environment_name: ExampleSpringVaadin14-env
        region: eu-west-3
        deployment_package: target/app.jar
